- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petsto .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: tag image
      command: docker tag petstor gajjalakesava/petsto

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: gajjalakesava
        password: dckr_pat_qgkR6VvfdfXaZlI3gMhTB7QRr4A


    - name: Push image
      command: docker push gajjalakesava/petsto

    - name: Run container
      command: docker run -d --name pet5 -p 3636:8080 gajjalakesava/petsto
