- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstores3 .
      args:
        chdir: /var/lib/jenkins/workspace/petshop

    - name: tag image
      command: docker tag petstores3 gajjalakesava/petstores3

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: gajjalakesava
        password: dckr_pat_GJ0t2QWB414XtWDqGr0eI4dhoJA


    - name: Push image
      command: docker push gajjalakesava/petstores3

    - name: Run container
      command: docker run -d --name pet3 -p 3635:8080 gajjalakesava/petstores3
